### ISSUE TITLE
[NEW] If agent cannot be queried for metadata, display error message on edit data system page

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#537]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

When the relevant agent is not able to be queried for metadata (possibly due to being defunct), the edit data system page simply does not show you the properties for the plugin.

**Describe the solution you'd like**
Please describe the desired behavior.

Give a helpful message describing the state of the agent.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have
considered.

**Comment by jhunt** [comment]
We are having a hard time reproducing this particular issue.

Using `testdev` as-is on master is a no-go; if you kill the agent metadata you get zero plugins in the dropdown (this is a problem in and of its own right, re:feedback, which we _will_  address).

We added a second agent into `testdev` (on :5445), but clearing one agents metadata only caused SHIELD to omit the metadata-less agent from the list of agents in the second dropdown, once we picked a plugin (because that agent effectively has "zero" plugins loaded).

We can do some defensive fixes to the way forms are rendered, and probably will anyway, but is it possible for you to provide some screenshots, or more details repro instructions, @thomasmitchell ?

**Comment by jhunt** [comment]
Spoke with Tom offline, and the salient bits of the discussion are:

1. This happened on edit, when the agent and plugin are already known (and therefore does not require a path from plugin → agent → metadata).
2. The agent may have had corrupt data because of a situation that #560 may have rendered impossible (moving forward)
3. Defensive code changes should commence, and we may not be able to verify a complete 100% fix; that's ok — we will just open a new issue with more details if/when it reappears.

**Comment by jhunt** [comment]
This is what we've got now.

<img width="720" alt="Screen Shot 2019-09-05 at 9 15 17 PM" src="https://user-images.githubusercontent.com/20047/64394049-4c5adf00-d022-11e9-9322-decd4c298257.png">
